[tool.poetry]
name = "parser"
version = "0.1.0"
description = ""
authors = ["SPGoding <15277496+SPGoding@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
mecha = "0.43.1"

[tool.poetry.dev-dependencies]
# pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
