[[language]]
name = "javascript"
indent = { tab-width = 3, unit = "\t" }
formatter = { command = "npx", args = [ "dprint", "fmt", "--stdin", "js" ] }

[[language]]
name = "typescript"
indent = { tab-width = 3, unit = "\t" }
formatter = { command = "npx", args = [ "dprint", "fmt", "--stdin", "ts" ] }
auto-format = true
